package exception_handling;

public class StartUp {

	public static void main(String[] args) {
	
//		int a;
//		
//		String nullString = null;
//		
//		try {
//			a =  10 / 0;
//		}
//		catch(ArithmeticException e) {
//			System.out.println(e);
//		}
//		
//		try {
//			nullString.length();
//		}
//		catch(NullPointerException e){
//			System.out.println(e);
//		}
				
		
		
//		try {
//			  int arr[]= {1,2};
//			  a = arr[5]; 
//		}
//		
//		catch(ArithmeticException e){
//			  System.out.println(e);
//		}
//	
//		catch(Exception e){
//			System.out.println(e);
//		}
//		finally {
//			System.out.println("FINALLY");
//		}
//		
		
		
		
//		try {
//			throw new ArithmeticException("exception");
//		}
//		catch(Exception e){
//			System.out.println(e);
//		}
		
		
		
//		try {
//		f();
//		}
//		catch(ArithmeticException e) {
//			System.out.print(e);
//		}
		
		

//		try {
//			customException();
//		}
//		catch(MyException e){
//			System.out.print(e);
//		}
//		
	
		
	}
	
	
//	static void f() throws ArithmeticException {
//		System.out.print("FF");
//		throw new ArithmeticException();
//	}
	
	
//	static void customException() throws MyException{
//		throw new MyException();
//	}


}
